/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.TourCtrl;

/**
 *
 * @author AmirHosein
 */
public class AdminControlPanel extends javax.swing.JFrame {
        TourCtrl tc = new TourCtrl();

    /**
     * Creates new form AdminControlPanelm
     */
    public AdminControlPanel() {
        initComponents();
        tc.currentDate(dateLbl, timeLbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alltoursLbl = new javax.swing.JLabel();
        editemployeeLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        addtourLbl = new javax.swing.JLabel();
        addemployeeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alltoursLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        alltoursLbl.setForeground(new java.awt.Color(0, 0, 0));
        alltoursLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Wine_Tour_30px_2.png"))); // NOI18N
        alltoursLbl.setText("All Tours");
        alltoursLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alltoursLblMouseClicked(evt);
            }
        });
        jPanel1.add(alltoursLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 46));

        editemployeeLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        editemployeeLbl.setForeground(new java.awt.Color(0, 0, 0));
        editemployeeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Registration_30px_1.png"))); // NOI18N
        editemployeeLbl.setText("Edit Employee");
        editemployeeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editemployeeLblMouseClicked(evt);
            }
        });
        jPanel1.add(editemployeeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 140, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 40, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 40, 46));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Anonymous_Mask_100px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 100));

        timeLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        timeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Alarm_Clock_35px_1.png"))); // NOI18N
        timeLbl.setText("Time");
        jPanel1.add(timeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 180, 50));

        dateLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Calendar_35px.png"))); // NOI18N
        dateLbl.setText("Date");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 190, 50));

        addtourLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addtourLbl.setForeground(new java.awt.Color(0, 0, 0));
        addtourLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Plus_30px.png"))); // NOI18N
        addtourLbl.setText("Add Tour");
        addtourLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtourLblMouseClicked(evt);
            }
        });
        jPanel1.add(addtourLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 46));

        addemployeeLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addemployeeLbl.setForeground(new java.awt.Color(0, 0, 0));
        addemployeeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Businessman_30px.png"))); // NOI18N
        addemployeeLbl.setText("Add Employee");
        addemployeeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addemployeeLblMouseClicked(evt);
            }
        });
        jPanel1.add(addemployeeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 40, 46));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 46));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 372, 200, 0));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1190, 740));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alltoursLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alltoursLblMouseClicked
        AllTours at = new AllTours();
        jDesktopPane1.add(at);
        at.show();
    }//GEN-LAST:event_alltoursLblMouseClicked

    private void editemployeeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editemployeeLblMouseClicked
        EditEmployee ee = new EditEmployee();
        jDesktopPane1.add(ee);
        ee.show();
    }//GEN-LAST:event_editemployeeLblMouseClicked

    private void addtourLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtourLblMouseClicked
        AddTour adt = new AddTour();
        jDesktopPane1.add(adt);
        adt.show();
    }//GEN-LAST:event_addtourLblMouseClicked

    private void addemployeeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addemployeeLblMouseClicked
        AddEmployee ad = new AddEmployee();
        jDesktopPane1.add(ad);
        ad.show();
    }//GEN-LAST:event_addemployeeLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            //</editor-fold>
            
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addemployeeLbl;
    private javax.swing.JLabel addtourLbl;
    private javax.swing.JLabel alltoursLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel editemployeeLbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables
}
