/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.TourCtrl;

/**
 *
 * @author Mohammad Reza
 */
public class EmployeeControllPanel extends javax.swing.JFrame {
    TourCtrl tc = new TourCtrl();
    /**
     * Creates new form EmployeeControllPanel
     */
    public EmployeeControllPanel() {
        initComponents();
        this.setTitle("ControllPanel");
        tc.currentDate(dateLbl, timeLbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        alltoursLbl2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        addtourLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(975, 620));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alltoursLbl2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        alltoursLbl2.setForeground(new java.awt.Color(0, 0, 0));
        alltoursLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Wine_Tour_30px_2.png"))); // NOI18N
        alltoursLbl2.setText("All Tours");
        alltoursLbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alltoursLbl2MouseClicked(evt);
            }
        });
        jPanel3.add(alltoursLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 40, 46));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Customer_Support_100px.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 100));

        timeLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        timeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Alarm_Clock_35px_1.png"))); // NOI18N
        timeLbl.setText("Time");
        jPanel3.add(timeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 50));

        dateLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Calendar_35px.png"))); // NOI18N
        dateLbl.setText("Date");
        jPanel3.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 190, 50));

        addtourLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addtourLbl.setForeground(new java.awt.Color(0, 0, 0));
        addtourLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Plus_30px.png"))); // NOI18N
        addtourLbl.setText("Add Tour");
        addtourLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtourLblMouseClicked(evt);
            }
        });
        jPanel3.add(addtourLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Chevron_Right_35px_3.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 40, 46));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alltoursLbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alltoursLbl2MouseClicked
        AllTours at = new AllTours();
        jDesktopPane1.add(at);
        at.show();
    }//GEN-LAST:event_alltoursLbl2MouseClicked

    private void addtourLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtourLblMouseClicked
        AddTour adt = new AddTour();
        jDesktopPane1.add(adt);
        adt.show();
    }//GEN-LAST:event_addtourLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeControllPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeControllPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeControllPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeControllPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeControllPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addtourLbl;
    private javax.swing.JLabel alltoursLbl2;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables
}
