/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.TourCtrl;

/**
 *
 * @author AmirHosein
 */
public class UserHome extends javax.swing.JFrame {
    TourCtrl tc = new TourCtrl();

    /**
     * Creates new form UserHome
     */
     String luser;
    public UserHome(String loginUser) {
        initComponents();
        this.luser = loginUser;
        welcomeLbl.setText("Welcome  "+luser);
        tc.currentDate(dateLbl, timeLbl);
    }

    public UserHome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reserveLbl = new javax.swing.JLabel();
        searchLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        welcomeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1175, 642));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reserveLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        reserveLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Luggage_Trolley_35px_1.png"))); // NOI18N
        reserveLbl.setText("Reserve Tours");
        reserveLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveLblMouseClicked(evt);
            }
        });
        jPanel1.add(reserveLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 128, 46));

        searchLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_Property_30px_1.png"))); // NOI18N
        searchLbl.setText("SEARCH");
        searchLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLblMouseClicked(evt);
            }
        });
        jPanel1.add(searchLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Forward_35px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 180, 40, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Forward_35px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 260, 40, 46));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Guest_Male_100px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 100));

        timeLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        timeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Alarm_Clock_35px_1.png"))); // NOI18N
        timeLbl.setText("Time");
        jPanel1.add(timeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 180, 50));

        dateLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Calendar_35px.png"))); // NOI18N
        dateLbl.setText("Date");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 180, 50));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        welcomeLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jDesktopPane1.setLayer(welcomeLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reserveLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveLblMouseClicked
        ReservedTour rt = new ReservedTour(luser);
        jDesktopPane1.add(rt);
        rt.show();
    }//GEN-LAST:event_reserveLblMouseClicked

    private void searchLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLblMouseClicked
        Search s = new Search(luser);
        jDesktopPane1.add(s);
        s.show();
    }//GEN-LAST:event_searchLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel reserveLbl;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
